import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./Component/sidebar/page";
import header from "./Component/header/page";
import Header from "./Component/header/page";

// Updated paths matching your exact folder structure uppercase letters


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Radish Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-screen w-screen overflow-hidden bg-slate-50 flex flex-row">
        
        {/* 1. Sidebar on the left */}
       <Sidebar/>

        {/* 2. Content workspace on the right */}
        <div className="flex-1 flex flex-col min-w-0  h-full relative">
          
          {/* Dynamic header at the top */}
         
          <Header/>
          {/* Main subpage content (e.g., your banner upload table) */}
          <main className="flex-1 overflow-y-auto">
            {children}
          </main>

        </div>

      </body>
    </html>
  );
}